IMAGE_NAME=127.0.0.1:5000/deep-mnist-training
IMAGE_VERSION=0.2

build_image:
	@set -x && docker build -f ./Dockerfile.training --force-rm=true -t $(IMAGE_NAME):$(IMAGE_VERSION) .

check_container:
	@set -x && docker run --rm -it $(IMAGE_NAME):$(IMAGE_VERSION) bash

run_container:
	@set -x && docker run --rm -it $(IMAGE_NAME):$(IMAGE_VERSION)

push_image:
	@set -x && docker push $(IMAGE_NAME):$(IMAGE_VERSION)

